### ISSUE TITLE
Research, Implement and Document AskSusi with Facebook

### ISSUE THREAD

**Issue by mariobehling** [loklak/asksusi_messengers#2]
Parent issue is #1 
* [ ] Add a folder "Facebook" with the code to the repository
* [ ] Add basic info in the Readme.md and also add a Readme.md with more details into the folder
* [ ] Give all info about required keys, access etc in the folders Readme.md
* [ ] Provide full access to other loklak core contributors

**Comment by sudheesh001** [comment]
- Architectural decision - https://github.com/loklak/asksusi_messengers/issues/3#issuecomment-238258774
- Blog post on facebook messenger service integration - http://blog.loklak.net/setting-up-susis-capabilities-on-facebook-messenger/
- Granted Admin access to facebook page and developer application to Michael and Mario
- Added the rest of the team members to test susi integration on facebook page messenger
- Will share the key for the application in private over in private with Mario and Michael and close this. (Heroku instance share, contains key in ENV)
